In [2]:
import pandas as pd

In [4]:
week_pricing = pd.read_csv("agriBORA_maize_prices_week_46.csv")
week_pricing.head()

      Week       County  AvgPricePerBag  BagSizeKg  AvgPricePerKg
0  2025-46       Kiambu            3450         90      38.333333
1  2025-46    Kirinyaga            3500         90      38.888889
2  2025-46      Mombasa            3250         90      36.111111
3  2025-46      Nairobi            3312         90      36.800000
4  2025-46  Uasin-Gishu            2990         90      33.222222

In [14]:
historical_pricing_data = pd.read_csv("kamis_maize_prices.csv")
historical_pricing_data.head()

,Commodity_Classification,Commodity,Classification,County,Market,Date,Year,Month,Year_Month,WeekofYear,Year_Week,SupplyVolume,Retail,Wholesale,Unit
0,Dry_White_Maize,Dry_Maize,White_Maize,Baringo,Kabarnet_Market,2021-05-24,2021,5,2021-05,21,2021-21,2700.0,30.0,25.00,Kg
1,Dry_White_Maize,Dry_Maize,White_Maize,Baringo,Marigat_Market,2021-05-24,2021,5,2021-05,21,2021-21,14000.0,30.0,27.00,Kg
2,Dry_White_Maize,Dry_Maize,White_Maize,Baringo,Marigat_Market,2021-05-24,2021,5,2021-05,21,2021-21,14000.0,30.0,27.00,Kg
3,Dry_Maize_Mixed_Traditional,Dry_Maize,Mixed_Traditional,Baringo,Eldama_Ravine_Market,2021-05-24,2021,5,2021-05,21,2021-21,900.0,40.0,22.22,Kg
4,Dry_White_Maize,Dry_Maize,White_Maize,Baringo,Marigat_Market,2021-05-24,2021,5,2021-05,21,2021-21,14000.0,30.0,27.00,Kg

In [16]:
print(historical_pricing_data['County'].value_counts())

County
Nairobi            2125
Nakuru             1755
Siaya              1709
Kirinyaga          1216
Migori             1072
Kisumu              866
Uasin-Gishu         826
Nandi               686
Kisii               668
Vihiga              613
Tharaka-Nithi       602
Trans-Nzoia         589
Meru                587
Embu                580
Nyeri               518
West-Pokot          496
Baringo             470
Kajiado             427
Nyamira             404
Mandera             402
Kwale               394
Bomet               387
Kitui               380
Homa-Bay            371
Nyandarua           351
Machakos            329
Taita-Taveta        316
Bungoma             275
Makueni             256
Busia               243
Kakamega            237
Kericho             228
Elgeyo-Marakwet     221
Garissa             216
Lamu                183
Laikipia            166
Muranga             161
Turkana             128
Mombasa              95
Kiambu               79
Narok                59
Kilifi               52
Tana-River           46
Wajir                45
Isiolo               37
Samburu              20
Marsabit              2
Name: count, dtype: int64

In [20]:
rows_to_drop =

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1049116138.py, line 1)

In [8]:
raw_historical_prices = pd.read_csv("kamis_maize_prices_raw.csv")
raw_historical_prices.head()

,Commodity,Classification,Grade,Sex,Market,Wholesale,Retail,Supply Volume,County,Date,Unit,Source,Year,Month,Year-Month,Week
0,dry maize,white maize,-,-,kawangware,55.0,65.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
1,dry maize,white maize,-,-,kipkaren,65.0,80.0,10000.0,Kakamega,2025-07-31,NaN,NaN,2025,July,2025-07,31
2,dry maize,white maize,-,-,kangemi market,NaN,55.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
3,dry maize,yellow maize,-,-,gikomba,77.78,100.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
4,dry maize,white maize,-,-,gikomba,52.22,65.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31

In [11]:
raw_historical_prices.drop('Grade', axis=1, inplace=True)

In [12]:
raw_historical_prices.drop('Sex', axis=1, inplace=True)

In [13]:
raw_historical_prices.head()

,Commodity,Classification,Market,Wholesale,Retail,Supply Volume,County,Date,Unit,Source,Year,Month,Year-Month,Week
0,dry maize,white maize,kawangware,55.0,65.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
1,dry maize,white maize,kipkaren,65.0,80.0,10000.0,Kakamega,2025-07-31,NaN,NaN,2025,July,2025-07,31
2,dry maize,white maize,kangemi market,NaN,55.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
3,dry maize,yellow maize,gikomba,77.78,100.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31
4,dry maize,white maize,gikomba,52.22,65.0,NaN,Nairobi,2025-07-31,NaN,NaN,2025,July,2025-07,31

In [17]:
print(raw_historical_prices['County'].value_counts())

County
Nairobi            2296
Nakuru             1969
Siaya              1724
Kirinyaga          1216
Migori             1073
Kisumu              915
Uasin-Gishu         827
Nandi               689
Kisii               669
Vihiga              616
Trans-Nzoia         605
Tharaka-Nithi       602
Meru                587
Embu                581
Nyeri               519
West-Pokot          506
Kajiado             486
Baringo             470
Mandera             415
Nyamira             411
Kwale               394
Bomet               387
Kitui               381
Homa-bay            371
Nyandarua           351
Machakos            329
Taita-Taveta        323
Bungoma             295
Makueni             261
Busia               246
Kakamega            243
Elgeyo-Marakwet     233
Kericho             228
Garissa             216
Lamu                183
Laikipia            173
Muranga             161
Turkana             132
Mombasa              96
Kiambu               80
Narok                60
Kilifi               52
Tana-River           46
Wajir                45
Isiolo               37
Samburu              24
Marsabit              2
Name: count, dtype: int64